export const USER_GET_EXISTING_DETAILS = 'USER_GET_EXISTING_DETAILS';
export const USER_EDIT_GENERAL_INFO = 'USER_CHANGE_GENERAL_INFO';
export const USER_EDIT_EMAIL = 'USER_EDIT_EMAIL';
export const USER_EDIT_PASSWORD = 'USER_EDIT_PASSWORD';
export const USER_CHANGE_ISNEWUSER_VALUE = 'USER_CHANGE_ISNEWUSER_VALUE';
