export const USER_RETRIEVE_RECORD = 'USER_RETRIEVE_RECORD';
export const USER_ADD_NEW_RECORD = 'USER_ADD_NEW_RECORD';
export const USER_EDIT_RECORD = 'USER_EDIT_RECORD';
export const USER_DELETE_RECORD = 'USER_DELETE_RECORD';
