export const USER_GET_EXISTING_PROGRAMS = 'USER_GET_EXISTING_PROGRAMS';
export const USER_ADD_NEW_PROGRAM = 'USER_ADD_NEW_PROGRAM';
export const USER_EDIT_PROGRAM = 'USER_EDIT_PROGRAM';
export const USER_DELETE_PROGRAM = 'USER_DELETE_PROGRAM';

export const USER_ADD_TO_PROGRAM_COUNT = 'USER_ADD_TO_PROGRAM_COUNT';
