export const USER_GET_PROGRAM_EXERCISES = 'USER_GET_PROGRAM_EXERCISES';
export const USER_ADD_PROGRAM_EXERCISE = 'USER_ADD_PROGRAM_EXERCISE';
export const USER_DELETE_PROGRAM_EXERCISE = 'USER_DELETE_PROGRAM_EXERCISE';

//ADDING and DELETING rest exercises:
export const USER_ADD_REST = 'USER_ADD_REST';
export const USER_DELETE_REST = 'USER_DELETE_REST';
