export const NEW_PROGRAM_EXERCISE = 'NEW_PROGRAM_EXERCISE';
export const EXISTING_STAT_PROGRAM_EXERCISE = 'EXISTING_STAT_PROGRAM_EXERCISE';
export const MAIN_LIFT_PROGRAM_EXERCISE = 'MAIN_LIFT_PROGRAM_EXERCISE';
export const PYRAMID_PROGRAM_EXERCISE = 'PYRAMID_PROGRAM_EXERCISE';
export const CARDIO_PROGRAM_EXERCISE = 'CARDIO_PROGRAM_EXERCISE';
