export const USER_ADD_NEW_SQUAT = 'USER_ADD_NEW_SQUAT';
export const USER_ADD_NEW_DEADLIFT = 'USER_ADD_NEW_DEADLIFT';
export const USER_ADD_NEW_BENCH = 'USER_ADD_NEW_BENCH';
export const USER_GET_EXISTING_DATA = 'USER_GET_EXISTING_DATA';
